# Pre-commit hooks for code quality and security
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        args: ['-ll', '--exclude', '.venv,tests']
        
  # Code formatting (optional but recommended)
  - repo: https://github.com/psf/black
    rev: '23.12.1'
    hooks:
      - id: black
        language_version: python3.10
        args: ['--line-length', '120', '--skip-string-normalization']
        
  # Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '120']
        
  # Linting
  - repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        args: ['--max-line-length', '120', '--extend-ignore', 'E203,W503']
        
  # Check for hardcoded secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: 'v1.4.0'
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']